# Generated by Django 5.2.4 on 2025-08-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='max_dose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty if no maximum dose', max_digits=5, null=True),
        ),
    ]
