# Generated by Django 5.2.4 on 2025-08-02 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_alter_medication_max_dose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=20)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('climate_suitability', models.CharField(choices=[('arid', 'Arid/Hot'), ('temperate', 'Temperate'), ('cold', 'Cold'), ('all', 'All Climates')], max_length=20)),
                ('avg_weight_kg', models.PositiveIntegerField(help_text='Average weight in kilograms')),
                ('lifespan_years', models.PositiveIntegerField(help_text='Typical lifespan in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('distinguishing_features', models.TextField(blank=True)),
                ('milk_yield', models.CharField(blank=True, help_text='e.g., 5-8L/day for dairy breeds', max_length=50)),
                ('meat_quality_rating', models.PositiveIntegerField(blank=True, help_text='Rating 1-5 (5=best)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('egg_production', models.CharField(blank=True, help_text='e.g., 100-120/year for poultry', max_length=50)),
                ('disease_resistance', models.TextField(blank=True)),
                ('feeding_requirements', models.TextField(blank=True)),
                ('special_considerations', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Optimal size: 600x400px', upload_to='breeds/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link (optional)')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Breeds',
                'ordering': ['species', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='medication',
            name='max_dose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty if no maximum dose', max_digits=10, null=True),
        ),
    ]
