# Generated by Django 5.2.4 on 2025-08-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_breed_alter_medication_max_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, help_text='Optimal size: 600x400px', upload_to='advisor/images/breeds/'),
        ),
    ]
